---
topbeat_app_dir: "{{ COMMON_APP_DIR }}/topbeat"
TOPBEAT_VERSION: 1.0.0
topbeat_url: "https://download.elastic.co/beats/topbeat/topbeat_{{ TOPBEAT_VERSION }}_amd64.deb"
BEAT_LOGSTASH_HOST: localhost
BEAT_LOGSTASH_PORT: 5044
topbeat_period_seconds: 30
TOPBEAT_PROCS:
  - '.*'
