---
KIBANA_SERVER_NAME: 192.168.33.10 
KIBANA_NGINX_PORT: 80
KIBANA_SSL_NGINX_PORT: 443

kibana_app_dir: /edx/app/kibana
kibana_file: "{{ kibana_version }}.tar.gz"
kibana_version: kibana-3.0.0
kibana_url: "https://download.elastic.co/kibana/kibana/{{ kibana_file }}"
