---
LOGSTASH_DAYS_TO_KEEP: 30
LOGSTASH_ROTATE: true
LOGSTASH_PORT: 5044
LOGSTASH_ELASTICSEARCH_HOST: localhost
LOGSTASH_ELASTICSEARCH_PORT: 9200
logstash_app_dir: "{{ COMMON_APP_DIR }}/logstash"
logstash_log_dir: "{{ COMMON_LOG_DIR }}/logstash"
logstash_data_dir: "{{ COMMON_DATA_DIR }}/logstash/file_logs"
logstash_syslog_port: 514
LOGSTASH_VERSION: 1.3.3
logstash_file: "logstash-{{ LOGSTASH_VERSION }}-flatjar.jar"
logstash_url: "https://download.elastic.co/logstash/logstash/{{ logstash_file }}" 
logstash_python_requirements:
  - pyes==0.19.0
LOGSTASH_PLUGINS:
  - logstash-input-beats
  - logstash-filter-multiline
  - logstash-output-file
logstash_scripts_repo: https://github.com/crashdump/logstash-elasticsearch-scripts
logstash_rotate_cron:
  hour: 5
  minute: 42
logstash_optimize_cron:
  hour: 6
  minute: 15
