---
LOGSTASH_DAYS_TO_KEEP: 30
LOGSTASH_ROTATE: true
logstash_app_dir: /edx/app/logstash
logstash_log_dir: /edx/var/log/logstash
logstash_data_dir: /edx/var/logstash/file_logs
logstash_syslog_port: 514
logstash_file: logstash-all-plugins_2.3.3-1_all.deb
logstash_url: "https://download.elastic.co/logstash/logstash/packages/debian/{{ logstash_file }}" 
logstash_python_requirements:
  - pyes==0.19.0
logstash_scripts_repo: https://github.com/crashdump/logstash-elasticsearch-scripts
logstash_rotate_cron:
  hour: 5
  minute: 42
logstash_optimize_cron:
  hour: 6
  minute: 15

LOGSTASH_PORT: 5044
LOGSTASH_HOST: localhost
