---
LOGSTASH_DAYS_TO_KEEP: 30
LOGSTASH_ROTATE: true
logstash_app_dir: /edx/app/logstash
logstash_log_dir: /edx/var/log/logstash
logstash_data_dir: /edx/var/logstash/file_logs
logstash_file: logstash-1.3.3-flatjar.jar
logstash_url: "https://download.elastic.co/logstash/logstash/{{ logstash_file }}" 
logstash_python_requirements:
  - pyes==0.19.0
logstash_scripts_repo: https://github.com/crashdump/logstash-elasticsearch-scripts
logstash_rotate_cron:
  hour: 5
  minute: 42
logstash_optimize_cron:
  hour: 6
  minute: 15

logstash_listen_port_lumberjack: 5000

logstash_elasticsearch_host: localhost

logstash_local_syslog_path: /var/log/syslog
logstash_monitor_local_syslog: true

logstash_enabled_on_boot: yes
