- name: Ensure {{ filebeat_app_dir }} exists
  file: path={{ filebeat_app_dir }} state=directory owner=root group=root mode=0777

- name: ensure we have the specified filebeat release
  get_url: url={{ filebeat_url }} dest=/tmp/{{ filebeat_file }}

- name: Install filebeat
  shell: dpkg --skip-same-version -i /tmp/{{ filebeat_file }}
  register: dpkg_result

- name: copy config
  template:
    src: filebeat.yml.j2
    dest: "/etc/filebeat/filebeat.yml"
    mode: 0744

- name: create symlink to {{ filebeat_app_dir }} for config
  file: src="/etc/filebeat/filebeat.yml" dest="{{ filebeat_app_dir }}/filebeat.yml" state=link

- name: allow filebeat to access logs
  file: 
    path: /edx/var/log
    mode: 0777
    recurse: yes

- name: Ensure filebeat is started and enabled on boot.
  service: name=filebeat state=started enabled=yes

