---
- name: Set up jumpbox ({{ env }})
  hosts: tag_Name_jumpbox_{{ env }}
  sudo: True
  vars_files:
    - "{{ secure_dir }}/vars/{{ env }}/jumpbox.yml"
  vars:
    secure_dir: '../../configuration-secure/ansible'
    FILEBEAT_LOGSTASH_HOST: localhost
    TOPBEAT_LOGSTASH_HOST: localhost
  roles:
    - role: common
      tags: common
    - filebeat
    - topbeat
