- name: Configure instance(s)
  hosts: tag_send_logs_true:&tag_environment_{{ env }}
  sudo: True
  gather_facts: True
  vars:
    FILEBEAT_LOGSTASH_HOST: localhost
    TOPBEAT_LOGSTASH_HOST: localhost
  roles:
    - role: filebeat
      when: FILEBEAT_LOGSTASH_HOST != ""
    - role: topbeat
      when: TOPBEAT_LOGSTASH_HOST != ""
