- hosts: ~tag_Name_{{ machine }}_{{ env }}
  sudo: True
  vars:
    secure_dir: '../../configuration-secure/ansible'
  vars_files:
    - "{{ secure_dir }}/vars/{{ env }}/users.yml"
  roles:
    - role: user
      tags: users
