- name: Configure instance(s)
  hosts: all
  sudo: True
  gather_facts: True
  vars:
    LOGSTASH_ELASTICSEARCH_HOST: localhost
  roles:
    - common
    - oraclejdk
    - elasticsearch
    - logstash
    - filebeat
    - topbeat
