- hosts: logs
  gather_facts: yes

  vars:
     LOGGER_TYPE: receiver
     RSYSLOG_SERVER_HOST: 192.168.33.10
#    logstash_forwarder_logstash_server: logs
#    logstash_forwarder_ssl_certificate_file: logstash-forwarder.crt

  pre_tasks:
    - name: Update apt cache if needed.
      apt: update_cache=yes cache_valid_time=86400

  roles:
    - common
    - oraclejdk
    - nginx
    - elasticsearch
    - kibana
    - logstash
