- hosts: logs
  gather_facts: yes
  sudo: True

  vars:
     #local host when run inside devstack, IP of kibana/ealsticsearch host
     #run as two machines
     LOGSTASH_SERVER_HOST: localhost
     nginx_sites: [kibana]
     nginx_cfg:
       sites_enabled:
         kibana: link
       version_html: "{{ nginx_app_dir }}/versions.html"
       version_json: "{{ nginx_app_dir }}/versions.json"

  pre_tasks:
    - name: Update apt cache if needed.
      apt: update_cache=yes cache_valid_time=86400

  roles:
    - common
    - oraclejdk
    - nginx
    - elasticsearch
    - kibana
    - logstash
    - filebeat
    - topbeat
